/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceActivityRouteImport } from './routes/workspace-activity'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as TimeDashboardRouteImport } from './routes/time-dashboard'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HandoverDocumentationRouteImport } from './routes/handover-documentation'
import { Route as EquityRouteImport } from './routes/equity'
import { Route as EmployeeScoringRouteImport } from './routes/employee-scoring'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as BoardingRouteImport } from './routes/boarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BonusRouteRouteImport } from './routes/bonus/route'
import { Route as AlysonNotetakerRouteRouteImport } from './routes/alyson-notetaker/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BonusIndexRouteImport } from './routes/bonus/index'
import { Route as AlysonNotetakerIndexRouteImport } from './routes/alyson-notetaker/index'
import { Route as WorkspaceActivityUserEmailRouteImport } from './routes/workspace-activity.$userEmail'
import { Route as TimeDashboardPacingRouteImport } from './routes/time-dashboard.pacing'
import { Route as TimeDashboardUserIdRouteImport } from './routes/time-dashboard.$userId'
import { Route as EmployeeScoringUserEmailRouteImport } from './routes/employee-scoring.$userEmail'
import { Route as BonusSimulateRouteImport } from './routes/bonus/simulate'
import { Route as BonusPlansRouteImport } from './routes/bonus/plans'
import { Route as BonusAuditRouteImport } from './routes/bonus/audit'
import { Route as BonusApprovalsRouteImport } from './routes/bonus/approvals'
import { Route as AlysonNotetakerUnifiedMeetingsRouteImport } from './routes/alyson-notetaker/unified-meetings'
import { Route as AlysonNotetakerTasksRouteImport } from './routes/alyson-notetaker/tasks'
import { Route as AlysonNotetakerCalendarRouteImport } from './routes/alyson-notetaker/calendar'
import { Route as AlysonNotetakerAnalyticsRouteImport } from './routes/alyson-notetaker/analytics'
import { Route as ApiCronNotetakerTranscriptsRouteImport } from './routes/api/cron/notetaker-transcripts'
import { Route as ApiCronDailyReportsRouteImport } from './routes/api/cron/daily-reports'
import { Route as ApiAnalyticsUnifiedMeetingsRouteImport } from './routes/api/analytics/unified-meetings'
import { Route as AlysonNotetakerAnalyticsUnifiedMeetingsRouteImport } from './routes/alyson-notetaker/analytics.unified-meetings'
import { Route as ApiAnalyticsUnifiedMeetingsScheduleBotsRouteImport } from './routes/api/analytics/unified-meetings.schedule-bots'
import { Route as ApiAnalyticsUnifiedMeetingsRefreshRouteImport } from './routes/api/analytics/unified-meetings.refresh'
import { Route as ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRouteImport } from './routes/api/analytics/unified-meetings.$meetingId.schedule'

const WorkspaceActivityRoute = WorkspaceActivityRouteImport.update({
  id: '/workspace-activity',
  path: '/workspace-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeDashboardRoute = TimeDashboardRouteImport.update({
  id: '/time-dashboard',
  path: '/time-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoverDocumentationRoute = HandoverDocumentationRouteImport.update({
  id: '/handover-documentation',
  path: '/handover-documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const EquityRoute = EquityRouteImport.update({
  id: '/equity',
  path: '/equity',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeScoringRoute = EmployeeScoringRouteImport.update({
  id: '/employee-scoring',
  path: '/employee-scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardingRoute = BoardingRouteImport.update({
  id: '/boarding',
  path: '/boarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusRouteRoute = BonusRouteRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => rootRouteImport,
} as any)
const AlysonNotetakerRouteRoute = AlysonNotetakerRouteRouteImport.update({
  id: '/alyson-notetaker',
  path: '/alyson-notetaker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusIndexRoute = BonusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BonusRouteRoute,
} as any)
const AlysonNotetakerIndexRoute = AlysonNotetakerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlysonNotetakerRouteRoute,
} as any)
const WorkspaceActivityUserEmailRoute =
  WorkspaceActivityUserEmailRouteImport.update({
    id: '/$userEmail',
    path: '/$userEmail',
    getParentRoute: () => WorkspaceActivityRoute,
  } as any)
const TimeDashboardPacingRoute = TimeDashboardPacingRouteImport.update({
  id: '/pacing',
  path: '/pacing',
  getParentRoute: () => TimeDashboardRoute,
} as any)
const TimeDashboardUserIdRoute = TimeDashboardUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => TimeDashboardRoute,
} as any)
const EmployeeScoringUserEmailRoute =
  EmployeeScoringUserEmailRouteImport.update({
    id: '/$userEmail',
    path: '/$userEmail',
    getParentRoute: () => EmployeeScoringRoute,
  } as any)
const BonusSimulateRoute = BonusSimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => BonusRouteRoute,
} as any)
const BonusPlansRoute = BonusPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => BonusRouteRoute,
} as any)
const BonusAuditRoute = BonusAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => BonusRouteRoute,
} as any)
const BonusApprovalsRoute = BonusApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => BonusRouteRoute,
} as any)
const AlysonNotetakerUnifiedMeetingsRoute =
  AlysonNotetakerUnifiedMeetingsRouteImport.update({
    id: '/unified-meetings',
    path: '/unified-meetings',
    getParentRoute: () => AlysonNotetakerRouteRoute,
  } as any)
const AlysonNotetakerTasksRoute = AlysonNotetakerTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AlysonNotetakerRouteRoute,
} as any)
const AlysonNotetakerCalendarRoute = AlysonNotetakerCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AlysonNotetakerRouteRoute,
} as any)
const AlysonNotetakerAnalyticsRoute =
  AlysonNotetakerAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AlysonNotetakerRouteRoute,
  } as any)
const ApiCronNotetakerTranscriptsRoute =
  ApiCronNotetakerTranscriptsRouteImport.update({
    id: '/api/cron/notetaker-transcripts',
    path: '/api/cron/notetaker-transcripts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronDailyReportsRoute = ApiCronDailyReportsRouteImport.update({
  id: '/api/cron/daily-reports',
  path: '/api/cron/daily-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsUnifiedMeetingsRoute =
  ApiAnalyticsUnifiedMeetingsRouteImport.update({
    id: '/api/analytics/unified-meetings',
    path: '/api/analytics/unified-meetings',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlysonNotetakerAnalyticsUnifiedMeetingsRoute =
  AlysonNotetakerAnalyticsUnifiedMeetingsRouteImport.update({
    id: '/unified-meetings',
    path: '/unified-meetings',
    getParentRoute: () => AlysonNotetakerAnalyticsRoute,
  } as any)
const ApiAnalyticsUnifiedMeetingsScheduleBotsRoute =
  ApiAnalyticsUnifiedMeetingsScheduleBotsRouteImport.update({
    id: '/schedule-bots',
    path: '/schedule-bots',
    getParentRoute: () => ApiAnalyticsUnifiedMeetingsRoute,
  } as any)
const ApiAnalyticsUnifiedMeetingsRefreshRoute =
  ApiAnalyticsUnifiedMeetingsRefreshRouteImport.update({
    id: '/refresh',
    path: '/refresh',
    getParentRoute: () => ApiAnalyticsUnifiedMeetingsRoute,
  } as any)
const ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRoute =
  ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRouteImport.update({
    id: '/$meetingId/schedule',
    path: '/$meetingId/schedule',
    getParentRoute: () => ApiAnalyticsUnifiedMeetingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alyson-notetaker': typeof AlysonNotetakerRouteRouteWithChildren
  '/bonus': typeof BonusRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/boarding': typeof BoardingRoute
  '/documents': typeof DocumentsRoute
  '/employee-scoring': typeof EmployeeScoringRouteWithChildren
  '/equity': typeof EquityRoute
  '/handover-documentation': typeof HandoverDocumentationRoute
  '/help': typeof HelpRoute
  '/leave': typeof LeaveRoute
  '/payroll': typeof PayrollRoute
  '/performance': typeof PerformanceRoute
  '/reports': typeof ReportsRoute
  '/team': typeof TeamRoute
  '/time-dashboard': typeof TimeDashboardRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/workspace-activity': typeof WorkspaceActivityRouteWithChildren
  '/alyson-notetaker/analytics': typeof AlysonNotetakerAnalyticsRouteWithChildren
  '/alyson-notetaker/calendar': typeof AlysonNotetakerCalendarRoute
  '/alyson-notetaker/tasks': typeof AlysonNotetakerTasksRoute
  '/alyson-notetaker/unified-meetings': typeof AlysonNotetakerUnifiedMeetingsRoute
  '/bonus/approvals': typeof BonusApprovalsRoute
  '/bonus/audit': typeof BonusAuditRoute
  '/bonus/plans': typeof BonusPlansRoute
  '/bonus/simulate': typeof BonusSimulateRoute
  '/employee-scoring/$userEmail': typeof EmployeeScoringUserEmailRoute
  '/time-dashboard/$userId': typeof TimeDashboardUserIdRoute
  '/time-dashboard/pacing': typeof TimeDashboardPacingRoute
  '/workspace-activity/$userEmail': typeof WorkspaceActivityUserEmailRoute
  '/alyson-notetaker/': typeof AlysonNotetakerIndexRoute
  '/bonus/': typeof BonusIndexRoute
  '/alyson-notetaker/analytics/unified-meetings': typeof AlysonNotetakerAnalyticsUnifiedMeetingsRoute
  '/api/analytics/unified-meetings': typeof ApiAnalyticsUnifiedMeetingsRouteWithChildren
  '/api/cron/daily-reports': typeof ApiCronDailyReportsRoute
  '/api/cron/notetaker-transcripts': typeof ApiCronNotetakerTranscriptsRoute
  '/api/analytics/unified-meetings/refresh': typeof ApiAnalyticsUnifiedMeetingsRefreshRoute
  '/api/analytics/unified-meetings/schedule-bots': typeof ApiAnalyticsUnifiedMeetingsScheduleBotsRoute
  '/api/analytics/unified-meetings/$meetingId/schedule': typeof ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/boarding': typeof BoardingRoute
  '/documents': typeof DocumentsRoute
  '/employee-scoring': typeof EmployeeScoringRouteWithChildren
  '/equity': typeof EquityRoute
  '/handover-documentation': typeof HandoverDocumentationRoute
  '/help': typeof HelpRoute
  '/leave': typeof LeaveRoute
  '/payroll': typeof PayrollRoute
  '/performance': typeof PerformanceRoute
  '/reports': typeof ReportsRoute
  '/team': typeof TeamRoute
  '/time-dashboard': typeof TimeDashboardRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/workspace-activity': typeof WorkspaceActivityRouteWithChildren
  '/alyson-notetaker/analytics': typeof AlysonNotetakerAnalyticsRouteWithChildren
  '/alyson-notetaker/calendar': typeof AlysonNotetakerCalendarRoute
  '/alyson-notetaker/tasks': typeof AlysonNotetakerTasksRoute
  '/alyson-notetaker/unified-meetings': typeof AlysonNotetakerUnifiedMeetingsRoute
  '/bonus/approvals': typeof BonusApprovalsRoute
  '/bonus/audit': typeof BonusAuditRoute
  '/bonus/plans': typeof BonusPlansRoute
  '/bonus/simulate': typeof BonusSimulateRoute
  '/employee-scoring/$userEmail': typeof EmployeeScoringUserEmailRoute
  '/time-dashboard/$userId': typeof TimeDashboardUserIdRoute
  '/time-dashboard/pacing': typeof TimeDashboardPacingRoute
  '/workspace-activity/$userEmail': typeof WorkspaceActivityUserEmailRoute
  '/alyson-notetaker': typeof AlysonNotetakerIndexRoute
  '/bonus': typeof BonusIndexRoute
  '/alyson-notetaker/analytics/unified-meetings': typeof AlysonNotetakerAnalyticsUnifiedMeetingsRoute
  '/api/analytics/unified-meetings': typeof ApiAnalyticsUnifiedMeetingsRouteWithChildren
  '/api/cron/daily-reports': typeof ApiCronDailyReportsRoute
  '/api/cron/notetaker-transcripts': typeof ApiCronNotetakerTranscriptsRoute
  '/api/analytics/unified-meetings/refresh': typeof ApiAnalyticsUnifiedMeetingsRefreshRoute
  '/api/analytics/unified-meetings/schedule-bots': typeof ApiAnalyticsUnifiedMeetingsScheduleBotsRoute
  '/api/analytics/unified-meetings/$meetingId/schedule': typeof ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alyson-notetaker': typeof AlysonNotetakerRouteRouteWithChildren
  '/bonus': typeof BonusRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/boarding': typeof BoardingRoute
  '/documents': typeof DocumentsRoute
  '/employee-scoring': typeof EmployeeScoringRouteWithChildren
  '/equity': typeof EquityRoute
  '/handover-documentation': typeof HandoverDocumentationRoute
  '/help': typeof HelpRoute
  '/leave': typeof LeaveRoute
  '/payroll': typeof PayrollRoute
  '/performance': typeof PerformanceRoute
  '/reports': typeof ReportsRoute
  '/team': typeof TeamRoute
  '/time-dashboard': typeof TimeDashboardRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/workspace-activity': typeof WorkspaceActivityRouteWithChildren
  '/alyson-notetaker/analytics': typeof AlysonNotetakerAnalyticsRouteWithChildren
  '/alyson-notetaker/calendar': typeof AlysonNotetakerCalendarRoute
  '/alyson-notetaker/tasks': typeof AlysonNotetakerTasksRoute
  '/alyson-notetaker/unified-meetings': typeof AlysonNotetakerUnifiedMeetingsRoute
  '/bonus/approvals': typeof BonusApprovalsRoute
  '/bonus/audit': typeof BonusAuditRoute
  '/bonus/plans': typeof BonusPlansRoute
  '/bonus/simulate': typeof BonusSimulateRoute
  '/employee-scoring/$userEmail': typeof EmployeeScoringUserEmailRoute
  '/time-dashboard/$userId': typeof TimeDashboardUserIdRoute
  '/time-dashboard/pacing': typeof TimeDashboardPacingRoute
  '/workspace-activity/$userEmail': typeof WorkspaceActivityUserEmailRoute
  '/alyson-notetaker/': typeof AlysonNotetakerIndexRoute
  '/bonus/': typeof BonusIndexRoute
  '/alyson-notetaker/analytics/unified-meetings': typeof AlysonNotetakerAnalyticsUnifiedMeetingsRoute
  '/api/analytics/unified-meetings': typeof ApiAnalyticsUnifiedMeetingsRouteWithChildren
  '/api/cron/daily-reports': typeof ApiCronDailyReportsRoute
  '/api/cron/notetaker-transcripts': typeof ApiCronNotetakerTranscriptsRoute
  '/api/analytics/unified-meetings/refresh': typeof ApiAnalyticsUnifiedMeetingsRefreshRoute
  '/api/analytics/unified-meetings/schedule-bots': typeof ApiAnalyticsUnifiedMeetingsScheduleBotsRoute
  '/api/analytics/unified-meetings/$meetingId/schedule': typeof ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alyson-notetaker'
    | '/bonus'
    | '/admin'
    | '/app'
    | '/attendance'
    | '/auth'
    | '/boarding'
    | '/documents'
    | '/employee-scoring'
    | '/equity'
    | '/handover-documentation'
    | '/help'
    | '/leave'
    | '/payroll'
    | '/performance'
    | '/reports'
    | '/team'
    | '/time-dashboard'
    | '/workflows'
    | '/workspace-activity'
    | '/alyson-notetaker/analytics'
    | '/alyson-notetaker/calendar'
    | '/alyson-notetaker/tasks'
    | '/alyson-notetaker/unified-meetings'
    | '/bonus/approvals'
    | '/bonus/audit'
    | '/bonus/plans'
    | '/bonus/simulate'
    | '/employee-scoring/$userEmail'
    | '/time-dashboard/$userId'
    | '/time-dashboard/pacing'
    | '/workspace-activity/$userEmail'
    | '/alyson-notetaker/'
    | '/bonus/'
    | '/alyson-notetaker/analytics/unified-meetings'
    | '/api/analytics/unified-meetings'
    | '/api/cron/daily-reports'
    | '/api/cron/notetaker-transcripts'
    | '/api/analytics/unified-meetings/refresh'
    | '/api/analytics/unified-meetings/schedule-bots'
    | '/api/analytics/unified-meetings/$meetingId/schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/attendance'
    | '/auth'
    | '/boarding'
    | '/documents'
    | '/employee-scoring'
    | '/equity'
    | '/handover-documentation'
    | '/help'
    | '/leave'
    | '/payroll'
    | '/performance'
    | '/reports'
    | '/team'
    | '/time-dashboard'
    | '/workflows'
    | '/workspace-activity'
    | '/alyson-notetaker/analytics'
    | '/alyson-notetaker/calendar'
    | '/alyson-notetaker/tasks'
    | '/alyson-notetaker/unified-meetings'
    | '/bonus/approvals'
    | '/bonus/audit'
    | '/bonus/plans'
    | '/bonus/simulate'
    | '/employee-scoring/$userEmail'
    | '/time-dashboard/$userId'
    | '/time-dashboard/pacing'
    | '/workspace-activity/$userEmail'
    | '/alyson-notetaker'
    | '/bonus'
    | '/alyson-notetaker/analytics/unified-meetings'
    | '/api/analytics/unified-meetings'
    | '/api/cron/daily-reports'
    | '/api/cron/notetaker-transcripts'
    | '/api/analytics/unified-meetings/refresh'
    | '/api/analytics/unified-meetings/schedule-bots'
    | '/api/analytics/unified-meetings/$meetingId/schedule'
  id:
    | '__root__'
    | '/'
    | '/alyson-notetaker'
    | '/bonus'
    | '/admin'
    | '/app'
    | '/attendance'
    | '/auth'
    | '/boarding'
    | '/documents'
    | '/employee-scoring'
    | '/equity'
    | '/handover-documentation'
    | '/help'
    | '/leave'
    | '/payroll'
    | '/performance'
    | '/reports'
    | '/team'
    | '/time-dashboard'
    | '/workflows'
    | '/workspace-activity'
    | '/alyson-notetaker/analytics'
    | '/alyson-notetaker/calendar'
    | '/alyson-notetaker/tasks'
    | '/alyson-notetaker/unified-meetings'
    | '/bonus/approvals'
    | '/bonus/audit'
    | '/bonus/plans'
    | '/bonus/simulate'
    | '/employee-scoring/$userEmail'
    | '/time-dashboard/$userId'
    | '/time-dashboard/pacing'
    | '/workspace-activity/$userEmail'
    | '/alyson-notetaker/'
    | '/bonus/'
    | '/alyson-notetaker/analytics/unified-meetings'
    | '/api/analytics/unified-meetings'
    | '/api/cron/daily-reports'
    | '/api/cron/notetaker-transcripts'
    | '/api/analytics/unified-meetings/refresh'
    | '/api/analytics/unified-meetings/schedule-bots'
    | '/api/analytics/unified-meetings/$meetingId/schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlysonNotetakerRouteRoute: typeof AlysonNotetakerRouteRouteWithChildren
  BonusRouteRoute: typeof BonusRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  AttendanceRoute: typeof AttendanceRoute
  AuthRoute: typeof AuthRoute
  BoardingRoute: typeof BoardingRoute
  DocumentsRoute: typeof DocumentsRoute
  EmployeeScoringRoute: typeof EmployeeScoringRouteWithChildren
  EquityRoute: typeof EquityRoute
  HandoverDocumentationRoute: typeof HandoverDocumentationRoute
  HelpRoute: typeof HelpRoute
  LeaveRoute: typeof LeaveRoute
  PayrollRoute: typeof PayrollRoute
  PerformanceRoute: typeof PerformanceRoute
  ReportsRoute: typeof ReportsRoute
  TeamRoute: typeof TeamRoute
  TimeDashboardRoute: typeof TimeDashboardRouteWithChildren
  WorkflowsRoute: typeof WorkflowsRoute
  WorkspaceActivityRoute: typeof WorkspaceActivityRouteWithChildren
  ApiAnalyticsUnifiedMeetingsRoute: typeof ApiAnalyticsUnifiedMeetingsRouteWithChildren
  ApiCronDailyReportsRoute: typeof ApiCronDailyReportsRoute
  ApiCronNotetakerTranscriptsRoute: typeof ApiCronNotetakerTranscriptsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace-activity': {
      id: '/workspace-activity'
      path: '/workspace-activity'
      fullPath: '/workspace-activity'
      preLoaderRoute: typeof WorkspaceActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-dashboard': {
      id: '/time-dashboard'
      path: '/time-dashboard'
      fullPath: '/time-dashboard'
      preLoaderRoute: typeof TimeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handover-documentation': {
      id: '/handover-documentation'
      path: '/handover-documentation'
      fullPath: '/handover-documentation'
      preLoaderRoute: typeof HandoverDocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equity': {
      id: '/equity'
      path: '/equity'
      fullPath: '/equity'
      preLoaderRoute: typeof EquityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-scoring': {
      id: '/employee-scoring'
      path: '/employee-scoring'
      fullPath: '/employee-scoring'
      preLoaderRoute: typeof EmployeeScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boarding': {
      id: '/boarding'
      path: '/boarding'
      fullPath: '/boarding'
      preLoaderRoute: typeof BoardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus': {
      id: '/bonus'
      path: '/bonus'
      fullPath: '/bonus'
      preLoaderRoute: typeof BonusRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alyson-notetaker': {
      id: '/alyson-notetaker'
      path: '/alyson-notetaker'
      fullPath: '/alyson-notetaker'
      preLoaderRoute: typeof AlysonNotetakerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus/': {
      id: '/bonus/'
      path: '/'
      fullPath: '/bonus/'
      preLoaderRoute: typeof BonusIndexRouteImport
      parentRoute: typeof BonusRouteRoute
    }
    '/alyson-notetaker/': {
      id: '/alyson-notetaker/'
      path: '/'
      fullPath: '/alyson-notetaker/'
      preLoaderRoute: typeof AlysonNotetakerIndexRouteImport
      parentRoute: typeof AlysonNotetakerRouteRoute
    }
    '/workspace-activity/$userEmail': {
      id: '/workspace-activity/$userEmail'
      path: '/$userEmail'
      fullPath: '/workspace-activity/$userEmail'
      preLoaderRoute: typeof WorkspaceActivityUserEmailRouteImport
      parentRoute: typeof WorkspaceActivityRoute
    }
    '/time-dashboard/pacing': {
      id: '/time-dashboard/pacing'
      path: '/pacing'
      fullPath: '/time-dashboard/pacing'
      preLoaderRoute: typeof TimeDashboardPacingRouteImport
      parentRoute: typeof TimeDashboardRoute
    }
    '/time-dashboard/$userId': {
      id: '/time-dashboard/$userId'
      path: '/$userId'
      fullPath: '/time-dashboard/$userId'
      preLoaderRoute: typeof TimeDashboardUserIdRouteImport
      parentRoute: typeof TimeDashboardRoute
    }
    '/employee-scoring/$userEmail': {
      id: '/employee-scoring/$userEmail'
      path: '/$userEmail'
      fullPath: '/employee-scoring/$userEmail'
      preLoaderRoute: typeof EmployeeScoringUserEmailRouteImport
      parentRoute: typeof EmployeeScoringRoute
    }
    '/bonus/simulate': {
      id: '/bonus/simulate'
      path: '/simulate'
      fullPath: '/bonus/simulate'
      preLoaderRoute: typeof BonusSimulateRouteImport
      parentRoute: typeof BonusRouteRoute
    }
    '/bonus/plans': {
      id: '/bonus/plans'
      path: '/plans'
      fullPath: '/bonus/plans'
      preLoaderRoute: typeof BonusPlansRouteImport
      parentRoute: typeof BonusRouteRoute
    }
    '/bonus/audit': {
      id: '/bonus/audit'
      path: '/audit'
      fullPath: '/bonus/audit'
      preLoaderRoute: typeof BonusAuditRouteImport
      parentRoute: typeof BonusRouteRoute
    }
    '/bonus/approvals': {
      id: '/bonus/approvals'
      path: '/approvals'
      fullPath: '/bonus/approvals'
      preLoaderRoute: typeof BonusApprovalsRouteImport
      parentRoute: typeof BonusRouteRoute
    }
    '/alyson-notetaker/unified-meetings': {
      id: '/alyson-notetaker/unified-meetings'
      path: '/unified-meetings'
      fullPath: '/alyson-notetaker/unified-meetings'
      preLoaderRoute: typeof AlysonNotetakerUnifiedMeetingsRouteImport
      parentRoute: typeof AlysonNotetakerRouteRoute
    }
    '/alyson-notetaker/tasks': {
      id: '/alyson-notetaker/tasks'
      path: '/tasks'
      fullPath: '/alyson-notetaker/tasks'
      preLoaderRoute: typeof AlysonNotetakerTasksRouteImport
      parentRoute: typeof AlysonNotetakerRouteRoute
    }
    '/alyson-notetaker/calendar': {
      id: '/alyson-notetaker/calendar'
      path: '/calendar'
      fullPath: '/alyson-notetaker/calendar'
      preLoaderRoute: typeof AlysonNotetakerCalendarRouteImport
      parentRoute: typeof AlysonNotetakerRouteRoute
    }
    '/alyson-notetaker/analytics': {
      id: '/alyson-notetaker/analytics'
      path: '/analytics'
      fullPath: '/alyson-notetaker/analytics'
      preLoaderRoute: typeof AlysonNotetakerAnalyticsRouteImport
      parentRoute: typeof AlysonNotetakerRouteRoute
    }
    '/api/cron/notetaker-transcripts': {
      id: '/api/cron/notetaker-transcripts'
      path: '/api/cron/notetaker-transcripts'
      fullPath: '/api/cron/notetaker-transcripts'
      preLoaderRoute: typeof ApiCronNotetakerTranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/daily-reports': {
      id: '/api/cron/daily-reports'
      path: '/api/cron/daily-reports'
      fullPath: '/api/cron/daily-reports'
      preLoaderRoute: typeof ApiCronDailyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/unified-meetings': {
      id: '/api/analytics/unified-meetings'
      path: '/api/analytics/unified-meetings'
      fullPath: '/api/analytics/unified-meetings'
      preLoaderRoute: typeof ApiAnalyticsUnifiedMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alyson-notetaker/analytics/unified-meetings': {
      id: '/alyson-notetaker/analytics/unified-meetings'
      path: '/unified-meetings'
      fullPath: '/alyson-notetaker/analytics/unified-meetings'
      preLoaderRoute: typeof AlysonNotetakerAnalyticsUnifiedMeetingsRouteImport
      parentRoute: typeof AlysonNotetakerAnalyticsRoute
    }
    '/api/analytics/unified-meetings/schedule-bots': {
      id: '/api/analytics/unified-meetings/schedule-bots'
      path: '/schedule-bots'
      fullPath: '/api/analytics/unified-meetings/schedule-bots'
      preLoaderRoute: typeof ApiAnalyticsUnifiedMeetingsScheduleBotsRouteImport
      parentRoute: typeof ApiAnalyticsUnifiedMeetingsRoute
    }
    '/api/analytics/unified-meetings/refresh': {
      id: '/api/analytics/unified-meetings/refresh'
      path: '/refresh'
      fullPath: '/api/analytics/unified-meetings/refresh'
      preLoaderRoute: typeof ApiAnalyticsUnifiedMeetingsRefreshRouteImport
      parentRoute: typeof ApiAnalyticsUnifiedMeetingsRoute
    }
    '/api/analytics/unified-meetings/$meetingId/schedule': {
      id: '/api/analytics/unified-meetings/$meetingId/schedule'
      path: '/$meetingId/schedule'
      fullPath: '/api/analytics/unified-meetings/$meetingId/schedule'
      preLoaderRoute: typeof ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRouteImport
      parentRoute: typeof ApiAnalyticsUnifiedMeetingsRoute
    }
  }
}

interface AlysonNotetakerAnalyticsRouteChildren {
  AlysonNotetakerAnalyticsUnifiedMeetingsRoute: typeof AlysonNotetakerAnalyticsUnifiedMeetingsRoute
}

const AlysonNotetakerAnalyticsRouteChildren: AlysonNotetakerAnalyticsRouteChildren =
  {
    AlysonNotetakerAnalyticsUnifiedMeetingsRoute:
      AlysonNotetakerAnalyticsUnifiedMeetingsRoute,
  }

const AlysonNotetakerAnalyticsRouteWithChildren =
  AlysonNotetakerAnalyticsRoute._addFileChildren(
    AlysonNotetakerAnalyticsRouteChildren,
  )

interface AlysonNotetakerRouteRouteChildren {
  AlysonNotetakerAnalyticsRoute: typeof AlysonNotetakerAnalyticsRouteWithChildren
  AlysonNotetakerCalendarRoute: typeof AlysonNotetakerCalendarRoute
  AlysonNotetakerTasksRoute: typeof AlysonNotetakerTasksRoute
  AlysonNotetakerUnifiedMeetingsRoute: typeof AlysonNotetakerUnifiedMeetingsRoute
  AlysonNotetakerIndexRoute: typeof AlysonNotetakerIndexRoute
}

const AlysonNotetakerRouteRouteChildren: AlysonNotetakerRouteRouteChildren = {
  AlysonNotetakerAnalyticsRoute: AlysonNotetakerAnalyticsRouteWithChildren,
  AlysonNotetakerCalendarRoute: AlysonNotetakerCalendarRoute,
  AlysonNotetakerTasksRoute: AlysonNotetakerTasksRoute,
  AlysonNotetakerUnifiedMeetingsRoute: AlysonNotetakerUnifiedMeetingsRoute,
  AlysonNotetakerIndexRoute: AlysonNotetakerIndexRoute,
}

const AlysonNotetakerRouteRouteWithChildren =
  AlysonNotetakerRouteRoute._addFileChildren(AlysonNotetakerRouteRouteChildren)

interface BonusRouteRouteChildren {
  BonusApprovalsRoute: typeof BonusApprovalsRoute
  BonusAuditRoute: typeof BonusAuditRoute
  BonusPlansRoute: typeof BonusPlansRoute
  BonusSimulateRoute: typeof BonusSimulateRoute
  BonusIndexRoute: typeof BonusIndexRoute
}

const BonusRouteRouteChildren: BonusRouteRouteChildren = {
  BonusApprovalsRoute: BonusApprovalsRoute,
  BonusAuditRoute: BonusAuditRoute,
  BonusPlansRoute: BonusPlansRoute,
  BonusSimulateRoute: BonusSimulateRoute,
  BonusIndexRoute: BonusIndexRoute,
}

const BonusRouteRouteWithChildren = BonusRouteRoute._addFileChildren(
  BonusRouteRouteChildren,
)

interface EmployeeScoringRouteChildren {
  EmployeeScoringUserEmailRoute: typeof EmployeeScoringUserEmailRoute
}

const EmployeeScoringRouteChildren: EmployeeScoringRouteChildren = {
  EmployeeScoringUserEmailRoute: EmployeeScoringUserEmailRoute,
}

const EmployeeScoringRouteWithChildren = EmployeeScoringRoute._addFileChildren(
  EmployeeScoringRouteChildren,
)

interface TimeDashboardRouteChildren {
  TimeDashboardUserIdRoute: typeof TimeDashboardUserIdRoute
  TimeDashboardPacingRoute: typeof TimeDashboardPacingRoute
}

const TimeDashboardRouteChildren: TimeDashboardRouteChildren = {
  TimeDashboardUserIdRoute: TimeDashboardUserIdRoute,
  TimeDashboardPacingRoute: TimeDashboardPacingRoute,
}

const TimeDashboardRouteWithChildren = TimeDashboardRoute._addFileChildren(
  TimeDashboardRouteChildren,
)

interface WorkspaceActivityRouteChildren {
  WorkspaceActivityUserEmailRoute: typeof WorkspaceActivityUserEmailRoute
}

const WorkspaceActivityRouteChildren: WorkspaceActivityRouteChildren = {
  WorkspaceActivityUserEmailRoute: WorkspaceActivityUserEmailRoute,
}

const WorkspaceActivityRouteWithChildren =
  WorkspaceActivityRoute._addFileChildren(WorkspaceActivityRouteChildren)

interface ApiAnalyticsUnifiedMeetingsRouteChildren {
  ApiAnalyticsUnifiedMeetingsRefreshRoute: typeof ApiAnalyticsUnifiedMeetingsRefreshRoute
  ApiAnalyticsUnifiedMeetingsScheduleBotsRoute: typeof ApiAnalyticsUnifiedMeetingsScheduleBotsRoute
  ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRoute: typeof ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRoute
}

const ApiAnalyticsUnifiedMeetingsRouteChildren: ApiAnalyticsUnifiedMeetingsRouteChildren =
  {
    ApiAnalyticsUnifiedMeetingsRefreshRoute:
      ApiAnalyticsUnifiedMeetingsRefreshRoute,
    ApiAnalyticsUnifiedMeetingsScheduleBotsRoute:
      ApiAnalyticsUnifiedMeetingsScheduleBotsRoute,
    ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRoute:
      ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRoute,
  }

const ApiAnalyticsUnifiedMeetingsRouteWithChildren =
  ApiAnalyticsUnifiedMeetingsRoute._addFileChildren(
    ApiAnalyticsUnifiedMeetingsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlysonNotetakerRouteRoute: AlysonNotetakerRouteRouteWithChildren,
  BonusRouteRoute: BonusRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  AttendanceRoute: AttendanceRoute,
  AuthRoute: AuthRoute,
  BoardingRoute: BoardingRoute,
  DocumentsRoute: DocumentsRoute,
  EmployeeScoringRoute: EmployeeScoringRouteWithChildren,
  EquityRoute: EquityRoute,
  HandoverDocumentationRoute: HandoverDocumentationRoute,
  HelpRoute: HelpRoute,
  LeaveRoute: LeaveRoute,
  PayrollRoute: PayrollRoute,
  PerformanceRoute: PerformanceRoute,
  ReportsRoute: ReportsRoute,
  TeamRoute: TeamRoute,
  TimeDashboardRoute: TimeDashboardRouteWithChildren,
  WorkflowsRoute: WorkflowsRoute,
  WorkspaceActivityRoute: WorkspaceActivityRouteWithChildren,
  ApiAnalyticsUnifiedMeetingsRoute:
    ApiAnalyticsUnifiedMeetingsRouteWithChildren,
  ApiCronDailyReportsRoute: ApiCronDailyReportsRoute,
  ApiCronNotetakerTranscriptsRoute: ApiCronNotetakerTranscriptsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
